spring.application.name=MyrmidonAI

# Configuracion DB
spring.datasource.url=jdbc:postgresql://localhost:5432/postgre_springsecurity_tutorial
spring.datasource.username=deamu
spring.datasource.password=deamu
spring.jpa.hibernate.ddl-auto=update

# Configuración de la IA
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3.1
spring.ai.ollama.embedding.model=nomic-embed-text
# Muestra las consultas SQL en la consola
spring.jpa.show-sql=true

# Dimensiones de Llama 3.1 , es necesario para la tabla de vectores
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.initialize-schema=true

# Carpeta donde se guardarán los PDFs fisicamente
myrmidon.upload-dir=uploads

logging.level.org.springframework.ai=DEBUG
logging.level.org.springframework.ai.chat.client.advisor=DEBUG